### ISSUE TITLE
Midterm Questions

### ISSUE THREAD

**Issue by MikeRed** [ataiya/igd#17]
Hello Dr. Tagliasacchi, I have a few questions about the midterm:

1) The Audio notes on Dropbox are a bit sparse; is this all we need to know for the midterm, or is there a section in the text that I need to read to fill in the gaps?

2) Will we get a cheat sheet for the second midterm as well?

3) Will we be tested on material from the 2 guest lectures that we had recently? As of writing this, the notes on Dropbox for these lectures are empty text files.

Thanks.

**Comment by taiya** [comment]
1. most of the learning for the audio happened in the lab. Make sure you understand the fundamentals of spatial sound and you'll be ok ;)
2. yes, the rules are identical to the midterm
3. no, I have left the text files there as placeholders to make sure I uploaded everything (the guest lectures are my way of slowing the class pace, so you can focus on the project)

**Comment by jonhealy1** [comment]
Will this exam be about the same length as the first one? Also I don't understand what the fundamentals of spatial sound are? In the lab we dragged and dropped audio files onto different objects. Are the marks from our first midterm being scaled or not? Some people said they are but I thought that in class you said that you didn't know. Thanks.

**Comment by jonhealy1** [comment]
Also will we have to do math with the Fourier transform? I know it's something we learned in class.

**Comment by taiya** [comment]
1) Will this exam be about the same length as the first one?

Yes

2) Also I don't understand what the fundamentals of spatial sound are? In the lab we dragged and dropped audio files onto different objects. 

In the lab, you dropped audio sources and microphones onto objects of the scene graph. Therefore, the sound system is aware of the position of sources and receivers, and sound changes according to how the microphone moves in the scene. Not much more than that, but your notes from the lecture will contain the other details.

3) Are the marks from our first midterm being scaled or not? Some people said they are but I thought that in class you said that you didn't know.

Correct, I don't know yet as I have to see how you guys perform. What I can ensure you is that your exam grade can only improve. 

4) Also will we have to do math with the Fourier transform? I know it's something we learned in class.

Anything that is on the slides/class/lab is a potential exam question. The level of detail that I require from you is proportional to the one of my lectures -- no more, potentially less

**Comment by jonhealy1** [comment]
Will you allow us to have the full 1 hour and 20 minutes to do the exam? Do you think that this is just a dumb class?

In all my 1st, 2nd, 3rd, and 4th year computer science courses I have received either an A or close to an A. I am realizing that I am going to probably fail this course and the grade point average I need to get into a Masters program will be trashed. 

I can't even save my grade with the final project because you make us do it in groups, my group members are swamped with work from other classes, and I know that it is going to probably be impossible to get a good grade on it anyways. 

A course in Unity should maybe be a pre requisite to this course. Maybe another Math/ Physics course as well (didn't help me though). 

The funny story about this is that I used my last elective to do this course and also that I was considering doing graduate work in graphics. See you next semester in the same course probably.

**Comment by taiya** [comment]
1) exam is 1h long, and no, I do not think that at all (I've had great students every semester)
2) grades are (typically) adjusted so that the top students in the class have an A+
(Any any recruiter would not just look at one grade)
3) this is supposed to be a learning experience, in the rest of your life you'll most likely work in a group. If your teammates did little the final report should state that and the grade will be adjusted to reflect that
4) a pure unity course is very unlikely to be offered in a research university. What you are looking for is a private professional school like Digipen
5) the only prerequisite we had was to know how to compute an integral and derivative of a polynomial, and perhaps a Taylor expansion to the first degree -all these are covered in your calculus class

Try to relax and focus on preparing on the exam, you'll likely do much better than you think!

**Comment by taiya** [comment]
Let me add one further note. As a recruiter myself I can not only tell you that a single grade has little to no meaning (we do outlier rejection), but also that having a portfolio of amazing projects to show off is incredibly more effective at getting you a position in a top school.

As a 2nd year course this is more a programming project, but the real key to shine above others in grad selections is with a semester invested as an assistant in a research

**Comment by taiya** [comment]
The NSERC USRA scholarships out department regularly announce are designed exactly for that purpose. And with an A/A+ GPA you are likely to obtain one.

Hope this helps
Best of luck
