### ISSUE TITLE
Assignment 2 - Change of Deadline?

### ISSUE THREAD

**Issue by connerleverett** [ataiya/igd#9]
Hi Dr. Tagliasacchi,

Is there any possibility of getting Assignment 2 due date changed from March 3rd to March 6th so we could have an extra weekend to work on it?

**Comment by taiya** [comment]
@connerleverett I cannot, but I can explain you why. 

We have 3x bonus late days that anybody can use. Therefore, we need to leave 3x days empty before the evaluation lab, so that everybody at that time will surely have turned in the homework. 

If you haven't used the late days, then you can use them now!! in practice the answer to your request depends on whether you have already used your late budget or not :)
